# Generated by Django 4.2.5 on 2023-09-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tilte',
            new_name='title',
        ),
    ]
