# Generated by Django 4.2.5 on 2023-09-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_tilte_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='your_default_email@example.com', max_length=254),
        ),
    ]
