# Generated by Django 4.2.5 on 2023-09-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
