# Generated by Django 4.2.5 on 2023-10-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_profile_bio_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=' Tell us about yourself ', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=' Default_name ', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.TextField(default='Links Ex:- Instagram,Linked-in', max_length=255),
        ),
    ]
