# Generated by Django 4.2.5 on 2023-10-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/u.jpg', null=True, upload_to='media'),
        ),
    ]
