# Generated by Django 4.2.5 on 2023-10-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='u.jpg', null=True, upload_to='avatars/'),
        ),
    ]
