# Generated by Django 4.2.5 on 2023-10-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/wee.jpg', null=True, upload_to='avatars/'),
        ),
    ]
